### ISSUE TITLE
Whole concepts in PDF format ?

### ISSUE THREAD

**Issue by sivaprabug** [asseco-pst/watch-your-language#1]
HI @daspinola @RodolfoGoncalves @dpcardoso

Whole concepts in PDF format ? Is very useful :+1: 

regards,
@gsivaprabu

**Comment by OrencioRodolfo** [comment]
Hi @gsivaprabu, 

Unfortunately we don't have it, because there are some gif images in some of the sections. Check 
the [event loop](https://github.com/Exictos-DCS/watch-your-language/blob/master/async.md#event-loop) for instance.

In case you create a PDF version of this, please share it with us. We'll be glad to see it :)

Cheers!

**Comment by daspinola** [comment]
I can give you a quick fix for it @gsivaprabu there is a cool API called [url-to-pdf-api](https://github.com/alvarcarto/url-to-pdf-api) and you can use it to extract to pdf a website.

Like @OrencioRodolfo said you won't be able to see the gifs (unless you press on them in the preview) and it has some other few visual nuances but it might help you get a more portable version of the repo.

A sample usage of the API would be:

```
https://url-to-pdf-api.herokuapp.com/api/render?url=<website_url>
```

Applying to the event loop url it looks like this:

```
https://url-to-pdf-api.herokuapp.com/api/render?url=https://github.com/Exictos-DCS/watch-your-language/blob/master/async.md#event-loop
```

The best scenario would be to have it in PDF but since it is not the case, at least for now, I do hope it serves your current needs.

PS: There is also the "CMD+P > Save as PDF" option
